[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build]
workspace=true
command = "cargo"
args = [ "build" ]

[tasks.build_release]
workspace=true
command = "cargo"
args = [ "build", "--release" ]

[tasks.build_flow]
run_task = { name = "build", fork = true }

[tasks.build_release_flow]
run_task = { name = "build_release", fork = true }

[tasks.check]
command = "cargo"
args = ["check", "--message-format=json-diagnostic-rendered-ansi"]
[tasks.check2]
command = "cargo"
args = ["check"]

[tasks.run]
workspace=false
script = '''
cd run
cp ../target/x86_64-unknown-uefi/debug/bootloader.efi esp/efi/boot/bootx64.efi
qemu-system-x86_64 -enable-kvm \
    -drive if=pflash,format=raw,readonly=on,file=OVMF_CODE.fd \
    -drive if=pflash,format=raw,readonly=on,file=OVMF_VARS.fd \
    -drive format=raw,file=fat:rw:esp \
    -m 4G \
    -device virtio-rng-pci
'''
dependencies = ["build_flow"]


[tasks.debug]
workspace=false
script = '''
cd run
cp ../target/x86_64-unknown-uefi/debug/bootloader.efi esp/efi/boot/bootx64.efi
qemu-system-x86_64 -enable-kvm \
    -drive if=pflash,format=raw,readonly=on,file=OVMF_CODE.fd \
    -drive if=pflash,format=raw,readonly=on,file=OVMF_VARS.fd \
    -drive format=raw,file=fat:rw:esp \
    -m 4G \
    -device virtio-rng-pci \
    -gdb tcp::12345 \
    -S
'''
dependencies = ["build_flow"]


[tasks.debug_detach]
workspace=false
script = '''
cd run
cp ../target/x86_64-unknown-uefi/debug/bootloader.efi esp/efi/boot/bootx64.efi
qemu-system-x86_64 -enable-kvm \
    -drive if=pflash,format=raw,readonly=on,file=OVMF_CODE.fd \
    -drive if=pflash,format=raw,readonly=on,file=OVMF_VARS.fd \
    -drive format=raw,file=fat:rw:esp \
    -m 4G \
    -device virtio-rng-pci \
    -gdb tcp::12345 \
    -S &
sleep 1
'''
dependencies = ["build_flow"]

[tasks.make_component]
workspace=false
script = '''
wasm-tools component new target/wasm32-unknown-unknown/debug/sample_app.wasm -o kernel/src/sample_app.wasm
cd precompile
cargo run -- ../kernel/src/sample_app.wasm
cd ..
rm kernel/src/sample_app.wasm
'''
dependencies = ["build_flow"]