[package]
name = "wasi-random"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.9.1", default-features = false, features = ["small_rng"] }
wasmtime = { version = "32.0.0", default-features = false, features = ["runtime", "component-model"] }
